# Generated by Django 4.0.5 on 2022-07-06 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dough', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Pizzas',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opsion1', models.CharField(max_length=50)),
                ('opsion2', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'toppings',
            },
        ),
        migrations.CreateModel(
            name='Pizza_topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.topping')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza')),
            ],
            options={
                'db_table': 'Pizza_topping',
            },
        ),
    ]
