# Generated by Django 4.0.5 on 2022-07-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_pizza_dough'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza_topping',
            old_name='Topping',
            new_name='topping',
        ),
        migrations.AlterModelTable(
            name='pizza_topping',
            table='pizza_topping',
        ),
    ]
