# Generated by Django 4.0.5 on 2022-07-06 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_rename_topping_pizza_topping_topping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_topping',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='pizza.pizza'),
        ),
        migrations.AlterField(
            model_name='pizza_topping',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='pizza.topping'),
        ),
    ]
