# Generated by Django 4.0.5 on 2022-07-06 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_alter_pizza_topping_pizza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_topping',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza'),
        ),
        migrations.AlterField(
            model_name='pizza_topping',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.topping'),
        ),
    ]
