# Generated by Django 4.0.5 on 2022-07-19 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStempModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('timestempmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.timestempmodel')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('post_number', models.CharField(max_length=10)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'storeusers',
            },
            bases=('user.timestempmodel',),
        ),
    ]
