# Generated by Django 4.0.5 on 2022-07-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actor_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actors_movies',
            table='actors_movies',
        ),
    ]
