# Generated by Django 4.0.5 on 2022-07-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_actors_movies_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors_movies',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors_a', to='movies.actor'),
        ),
        migrations.AlterField(
            model_name='actors_movies',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies_m', to='movies.movie'),
        ),
    ]
