# Generated by Django 4.0.5 on 2022-07-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_actors_movies_actor_alter_actors_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(related_name='movies', to='movies.movie'),
        ),
        migrations.DeleteModel(
            name='Actors_movies',
        ),
    ]
