# Generated by Django 4.0.5 on 2022-07-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_actor_movie_actors_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors_movies',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actorfk', to='movies.actor'),
        ),
        migrations.AlterField(
            model_name='actors_movies',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviefk', to='movies.movie'),
        ),
    ]
